import { firefox } from 'playwright';
const b = await firefox.launch(); const ctx = await b.newContext({ viewport:{width:1360,height:900} }); const page = await ctx.newPage();
page.on('pageerror', e=>console.log('PAGEERROR', e.message));
await page.goto('http://localhost:8088/', { waitUntil:'networkidle' });
await page.click('.demo-btn[data-demo="coach"]'); await page.waitForTimeout(700);
if (await page.locator('#tour-skip').count()) await page.click('#tour-skip').catch(()=>{});
await page.click('.nav-btn[data-view="playbook"]'); await page.waitForTimeout(400);
await page.locator('.scn-card:not(.scn-new)').first().click(); await page.waitForTimeout(400);
console.log('frame-label before anything:', await page.locator('#frame-label').textContent());
await page.click('#fs-btn'); await page.waitForTimeout(300);
console.log('stage-full?', await page.locator('#view-playbook.stage-full').count());
await page.mouse.move(400,300); await page.waitForTimeout(200);
console.log('fs-bar shown?', await page.locator('#fs-bar.show').count(), 'fsb-label=', await page.locator('#fsb-label').textContent());
const before = await page.locator('#fsb-label').textContent();
await page.click('#fsb-restart'); await page.waitForTimeout(150);
console.log('after restart:', await page.locator('#fsb-label').textContent(), 'frame-label:', await page.locator('#frame-label').textContent());
await page.click('#fsb-fwd'); await page.waitForTimeout(200);
console.log('after fwd:', await page.locator('#fsb-label').textContent(), 'frame-label:', await page.locator('#frame-label').textContent());
console.log('play-btn text (state):', await page.locator('#play-btn').textContent());
console.log('adjust-bar hidden?', await page.locator('#adjust-bar').isHidden().catch(()=>'n/a'));
await b.close();
