import { firefox } from 'playwright';
const b = await firefox.launch(); const ctx = await b.newContext({ viewport:{width:1360,height:900} }); const page = await ctx.newPage();
page.on('pageerror', e=>console.log('PAGEERROR', e.message));
await page.goto('http://localhost:8088/', { waitUntil:'networkidle' });
await page.click('.demo-btn[data-demo="coach"]'); await page.waitForTimeout(700);
if (await page.locator('#tour-skip').count()) await page.click('#tour-skip').catch(()=>{});
await page.click('.nav-btn[data-view="playbook"]'); await page.waitForTimeout(400);
await page.locator('.scn-card:not(.scn-new)').first().click(); await page.waitForTimeout(400);
await page.click('#scene3d-toggle'); await page.waitForTimeout(300);
await page.evaluate(() => {
  window.__orbitCalls = 0;
  const orig = MANIKIN.orbit;
  MANIKIN.orbit = function(...args) { window.__orbitCalls++; window.__lastArgs = args.slice(1); return orig.apply(MANIKIN, args); };
});
const box = await page.locator('#scene3d').boundingBox();
await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
await page.mouse.down();
await page.mouse.move(box.x+box.width/2+120, box.y+box.height/2-40, {steps:10});
await page.waitForTimeout(50);
await page.mouse.up();
await page.waitForTimeout(200);
console.log('orbit() calls during drag:', await page.evaluate(() => window.__orbitCalls));
console.log('last args:', await page.evaluate(() => window.__lastArgs));
await b.close();
