import { firefox } from 'playwright';
const b = await firefox.launch(); const ctx = await b.newContext({ viewport:{width:1360,height:900} }); const page = await ctx.newPage();
await page.goto('http://localhost:8088/', { waitUntil:'networkidle' });
await page.click('.demo-btn[data-demo="coach"]'); await page.waitForTimeout(700);
if (await page.locator('#tour-skip').count()) await page.click('#tour-skip').catch(()=>{});
await page.click('.nav-btn[data-view="playbook"]'); await page.waitForTimeout(400);
await page.locator('.scn-card:not(.scn-new)').first().click(); await page.waitForTimeout(400);
await page.click('#scene3d-toggle'); await page.waitForTimeout(300);
await page.evaluate(() => {
  const cv = document.querySelector('#scene3d');
  window.__pev = [];
  ['pointerdown','pointermove','pointerup'].forEach(t => cv.addEventListener(t, e => window.__pev.push(t+':'+e.pointerId+':'+e.clientX+','+e.clientY), true));
});
const box = await page.locator('#scene3d').boundingBox();
await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
await page.mouse.down();
await page.mouse.move(box.x+box.width/2+120, box.y+box.height/2-40, {steps:10});
await page.mouse.up();
await page.waitForTimeout(200);
console.log('events captured:', await page.evaluate(() => window.__pev.length));
console.log(await page.evaluate(() => window.__pev.slice(0,6)));
console.log('canvas style pointer-events:', await page.evaluate(() => getComputedStyle(document.querySelector('#scene3d')).pointerEvents));
console.log('canvas position/zindex:', await page.evaluate(() => { const s=getComputedStyle(document.querySelector('#scene3d')); return {pos:s.position, z:s.zIndex, w:s.width, h:s.height}; }));
console.log('elementFromPoint at centre is canvas?', await page.evaluate((b) => { const el = document.elementFromPoint(b.x+b.width/2-b.x, b.y+b.height/2-b.y); return el ? el.id||el.className : null; }, box));
await b.close();
